In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scypy as sp

In [55]:
sales = pd.read_csv(
    filepath_or_buffer="https://gist.githubusercontent.com/andron23/0675d643fe001b08a66271402a7b609b/raw/231deb6c35c43ca9089b197d94d7d48e093bfb06/sales_data.csv",
    parse_dates=["order_date"]
)
sales.head()

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region
0,1,101,1001,2022-02-15,2,500,1000,Карта,Север
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг
2,3,103,1003,2022-03-25,3,300,900,Карта,Запад
3,4,104,1001,2022-04-10,2,400,800,Карта,Восток
4,5,105,1004,2022-04-15,1,700,700,Наличные,Север

In [56]:
product = pd.read_csv(
    filepath_or_buffer="https://gist.githubusercontent.com/andron23/fc2b28de07d5017f951c559f51fcb286/raw/be9f8cd81b28f3c19d314ef908aa68e9f41ae975/products_data.csv",
).drop_duplicates()
product.head()

   product_id                 product_name    category manufacturer
0         101       Ноутбук HP Pavilion 15    Ноутбуки            A
1         102  Смартфон Samsung Galaxy S21   Смартфоны            B
2         103       Планшет Apple iPad Air    Планшеты            C
3         104     Наушники Sony WH-1000XM4    Наушники            D
4         105         Телевизор LG OLED CX  Телевизоры            E

In [57]:
merged = pd.merge(
    left=sales,
    right=product,
    left_on="product_id",
    right_on="product_id",
    how="right"
)
merged2 = merged.copy()
merged.head()

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region,product_name,category,manufacturer
0,1,101,1001,2022-02-15,2,500,1000,Карта,Север,Ноутбук HP Pavilion 15,Ноутбуки,A
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг,Смартфон Samsung Galaxy S21,Смартфоны,B
2,3,103,1003,2022-03-25,3,300,900,Карта,Запад,Планшет Apple iPad Air,Планшеты,C
3,4,104,1001,2022-04-10,2,400,800,Карта,Восток,Наушники Sony WH-1000XM4,Наушники,D
4,5,105,1004,2022-04-15,1,700,700,Наличные,Север,Телевизор LG OLED CX,Телевизоры,E

In [58]:
merged.head()
merged[merged.category == "Смартфоны"].region

1         Юг
6      Запад
11    Восток
16     Север
21        Юг
26     Запад
Name: region, dtype: object

In [59]:
merged2.head()

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region,product_name,category,manufacturer
0,1,101,1001,2022-02-15,2,500,1000,Карта,Север,Ноутбук HP Pavilion 15,Ноутбуки,A
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг,Смартфон Samsung Galaxy S21,Смартфоны,B
2,3,103,1003,2022-03-25,3,300,900,Карта,Запад,Планшет Apple iPad Air,Планшеты,C
3,4,104,1001,2022-04-10,2,400,800,Карта,Восток,Наушники Sony WH-1000XM4,Наушники,D
4,5,105,1004,2022-04-15,1,700,700,Наличные,Север,Телевизор LG OLED CX,Телевизоры,E

In [65]:
means = merged2.groupby(["manufacturer", "category"]).agg({"price_per_unit":"mean"}).reset_index()
means[means.category == "Ноутбуки"].price_per_unit.max() - means[means.category == "Ноутбуки"].price_per_unit.min()

np.float64(200.0)

In [66]:
def get_data():
    sales = pd.read_csv(
        filepath_or_buffer="https://gist.githubusercontent.com/andron23/0675d643fe001b08a66271402a7b609b/raw/231deb6c35c43ca9089b197d94d7d48e093bfb06/sales_data.csv",
        parse_dates=["order_date"]
    )
    product = pd.read_csv(
        filepath_or_buffer="https://gist.githubusercontent.com/andron23/fc2b28de07d5017f951c559f51fcb286/raw/be9f8cd81b28f3c19d314ef908aa68e9f41ae975/products_data.csv",
    )
    return (sales, product)

In [67]:
sal, prod = get_data()

In [68]:
sal.head()

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region
0,1,101,1001,2022-02-15,2,500,1000,Карта,Север
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг
2,3,103,1003,2022-03-25,3,300,900,Карта,Запад
3,4,104,1001,2022-04-10,2,400,800,Карта,Восток
4,5,105,1004,2022-04-15,1,700,700,Наличные,Север

In [70]:
sal.groupby("customer_id").agg({"total_price":"sum"}).reset_index().sort_values(by="total_price")

    customer_id  total_price
16         1017          300
12         1013          550
17         1018          700
15         1016          800
11         1012          900
4          1005         1200
13         1014         1200
14         1015         1350
7          1008         1750
3          1004         1900
1          1002         2000
9          1010         2050
10         1011         2050
8          1009         2650
5          1006         2850
0          1001         3150
6          1007         3500
2          1003         3550

In [71]:
prod.head()

   product_id                 product_name    category manufacturer
0         101       Ноутбук HP Pavilion 15    Ноутбуки            A
1         102  Смартфон Samsung Galaxy S21   Смартфоны            B
2         103       Планшет Apple iPad Air    Планшеты            C
3         104     Наушники Sony WH-1000XM4    Наушники            D
4         105         Телевизор LG OLED CX  Телевизоры            E

In [ ]:
inner = pd.merge(
    left=sales,
    right=prod,
    left_on="product_id",
    right_on="product_id",
    how="inner"
)

total_revenue = inner.total_price.sum()
tablet_revenue = inner[inner.category == "Планшеты"].total_price.sum()
(tablet_revenue / total_revenue).round(2)

np.float64(0.25)

In [82]:
inner.groupby("region").agg({"total_price":"sum"}).reset_index()
regs = ("Восток", "Юг")
inner[inner.region.isin(regs) & (inner.category == "Смартфоны")].groupby("region").agg({"total_price":"mean"})

        total_price
region
Восток       1100.0
Юг            700.0

In [84]:
inner.groupby("region").agg({"category":"nunique"}).reset_index()

   region  category
0  Восток         5
1   Запад         5
2   Север         5
3      Юг         5

In [85]:
prod.head()

   product_id                 product_name    category manufacturer
0         101       Ноутбук HP Pavilion 15    Ноутбуки            A
1         102  Смартфон Samsung Galaxy S21   Смартфоны            B
2         103       Планшет Apple iPad Air    Планшеты            C
3         104     Наушники Sony WH-1000XM4    Наушники            D
4         105         Телевизор LG OLED CX  Телевизоры            E

In [86]:
prod.groupby("manufacturer").agg({"category":"nunique"})

              category
manufacturer
A                    2
B                    3
C                    3
D                    3
E                    4

In [89]:
inner[(inner.category == "Планшеты") & (inner.region == "Север")]

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region,product_name,category,manufacturer
12,13,113,1010,2022-08-05,1,900,900,Наличные,Север,Планшет Huawei MatePad Pro,Планшеты,C

In [ ]:
inner[(inner.order_date.dt.month == 3 ) & (inner.region == "Юг")]

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region,product_name,category,manufacturer
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг,Смартфон Samsung Galaxy S21,Смартфоны,B
29,30,130,1018,2023-03-30,2,350,700,Карта,Юг,Телевизор Samsung The Frame,Телевизоры,B

In [93]:
catt = inner.groupby("customer_id").agg({"category":"nunique"}).reset_index()
catt[catt.category >= 3]

   customer_id  category
2         1003         3

In [99]:
(inner[(inner.manufacturer == "C" ) & (inner.region == "Север")].total_price.sum() / inner[(inner.region == "Север")].total_price.sum()).round(2)

np.float64(0.27)

In [101]:
inner.manufacturer.value_counts()

manufacturer
A    6
B    6
C    6
D    6
E    6
Name: count, dtype: int64

In [102]:
inner.groupby(["customer_id", "category", "manufacturer"]).agg({"order_id":"nunique"})

                                     order_id
customer_id category   manufacturer
1001        Наушники   D                    1
            Ноутбуки   A                    1
                       C                    1
1002        Смартфоны  B                    1
1003        Наушники   A                    2
            Планшеты   C                    1
            Смартфоны  C                    1
1004        Телевизоры D                    1
                       E                    1
1005        Ноутбуки   A                    1
1006        Планшеты   B                    1
            Смартфоны  D                    1
1007        Наушники   E                    1
            Ноутбуки   C                    1
1008        Ноутбуки   E                    1
            Планшеты   E                    1
1009        Наушники   A                    1
            Смартфоны  D                    1
1010        Планшеты   C                    1
            Телевизоры B                    1
1011        Наушники   A                    1
            Телевизоры B                    1
1012        Ноутбуки   C                    1
1013        Смартфоны  D                    1
1014        Планшеты   E                    1
1015        Телевизоры B                    1
1016        Планшеты   E                    1
1017        Смартфоны  D                    1
1018        Телевизоры B                    1

In [106]:
inner.groupby("order_id").agg({"quantity":"sum"}).reset_index().quantity.max()

np.int64(4)

In [107]:
inner.groupby("manufacturer").agg({"price_per_unit":"mean"})

              price_per_unit
manufacturer
A                 491.666667
B                 566.666667
C                 525.000000
D                 362.500000
E                 683.333333